/* 
 * Portuguese Brazil Translation by Fabio Oliva - fboliva@safenetworks.com
 */

/* charset */
#define CHARSET "iso-8859-1"

/* global */
#define CALLITFROMBROWSER "You should *not* call this program directly !"

/* start */
#define STARTGAMENICK1 "Nome ou apelido do jogador 1"
#define STARTGAMENICK2 "Nome ou apelido do jogador 2"
#define STARTGAMELEAVEBLANK "Deixe o campo do jogador 2 em branco se estiver jogando sozinho(a)."
#define STARTGAMEMAIL1 "Endereço de e-mail do jogador 1"
#define STARTGAMEMAIL2 "Endereço de e-mail do jogador 2"
#define STARTHASWHITE "Este jogador é branco"
#define STARTNEW "Iniciar novo jogo"
#define STARTGAMEID "ID do jogo"
#define STARTRESUME "Resumir jogo"
#define STARTFINISH "Um novo jogo foi iniciado. Verifique sua caixa de entrada de e-mails !"
#define STARTWAIT "Agora é só esperar pelo seu oponente..."
#define STARTSEARCH "Acessar um dos seguintes jogos"
#define STARTNUMBERGAMES "jogos"
#define STARTNUMBEROGAMES "jogos abertos"
#define STARTANEWGAME "Iniciar um jogo"
#define STARTRESUMEAGAME "Resumir um jogo"
#define STARTSENDMYGAMES "Envie-me meus jogos"
#define STARTMYMAIL "Meu endereço de e-mail"
#define STARTSEND "Enviar"
#define STARTSENDNOMAIL "Apenas listar os jogos"

/* mail */
#define MAILDEAR "Caríssimo(a)"
#define MAILMOVE "É o seu movimento agora. Sua senha é"
#define MAILURLRESUME "Acesse o link a seguir para acessar o jogo"
#define MAILURLVIEW "Acesso o link a seguir para ver o jogo"
#define MAILDONE "Seu movimento foi feito."
#define MAILINVITE "Você foi convidado para uma partida de xadrez"
#define MAILID "O ID do seu jogo é"
#define MAILBOARD "Seu tabuleiro está localizado em"
#define MAILWINNER "Você venceu o jogo!"
#define MAILOPCHECK "Seu oponente está em cheque!"
#define MAILPASS "Sua senha foi enviada por e-mail !"
#define MAILREMIS "Foi solicitado o empate"
#define MAILISREMIS "Empate !"
#define MAILGIVESUP "%s desistiu !"
#define MAILHIT "Hit"
#define MAILFINISHED "Este jogo está terminado!"
#define MAILAGAINST "contra"
#define MAILYOUWHITE "Você tem as peças brancas (topo da tela)"
#define MAILYOUBLACK "Você tem as peças pretas (baixo da tela)"

/* resume */
#define RESTITLE "Partida de xadrez: %s contra %s"
#define RESTURN "É a vez de %s jogar com as %s !"
#define RESTURNR "É sua escolha, %s !"
#define RESLAST "O úlitmo movimento foi"
#define RESPASS "Por favor, digite a senha"
#define RESMOVES "Movimentos até agora"
#define RESCHANGE "Por favor, selecione uma peça para trocar com o peão movido!"
#define RESMESSAGE "Mensagem"
#define RESREQUESTSENT "Sua requisição foi enviada"
#define RESREMREQ "Empate foi solicitado!"
#define RESMAILOF "Endereço e-mail de %s"
#define RESID "ID do jogo"
#define RESSTART "O jogo iniciou em"
#define RESFIXPASS "Senha fixa"
#define RESFIXPASSA "Redigite a senha fixa"
#define RESPASSWARN "Apenas um alerta para você: NÃO É SEGURO!<br>Qualquer um pode conseguí-la facilmente.<br>Então não use senhas padrão!"
#define RESNOMAILTOME "Eu não quero receber e-mails durante o jogo."

/* moved */
#define MOVEDFINISH "Seu movimento foi enviado. Por favor clique aqui para ver o tabuleiro novamente!"
#define MOVECANC "Seu movimento foi cancelado!"

/* sendgames */
#define SENDGAMESPLAY "Você está jogando os seguintes jogos"
#define SENDGAMESBYE "Tenha um bom dia"
#define SENDGAMESBACK "Seus jogos foram enviados para o seu endereço de e-mail!"
#define SENDGAMENOTFOUND "Não existem jogos para este endereço de e-mail"
#define SENDBACK "Voltar para a tela de login"

/* errors */
#define ERRORDEFAULT "Erro"
#define ERRORCREATE "Não foi possível criar o arquivo"
#define ERROROPEN "Não foi possível abrir o arquivo"
#define ERRORPIPE "Unable to open pipe"
#define ERRORID "O jogo requisitado não existe."
#define ERRORMEM "Estouro de memória"
#define ERRORMOV "Erro ao mover a peça"
#define ERRORPASS "Senha errada ou não preenchida!"
#define ERRORGAMEDIR "Não foi possível abrir o diretório"
#define ERRORGAMECOR "Os dados do jogo foram corrompidos"
#define ERRORMAILVALID "E-mail inválido"
#define ERRORMISMAIL "E-mail não digitado"
#define ERRORMISNICK "Nome/Apelido não digitado"
#define ERRORNICKLONG "O Nome/Apelido é muito longo"
#define ERRORMAILLONG "O e-mail é muito longo"
#define ERRORPASSLONG "Sua senha é muito longa"
#define ERROROLDBOARD "Sue tabuleiro mostra um movimento já realizado.... Você tem que recarregar o jogo!"
#define ERRORILLEGAL "Movimento Ilegal"
#define ERRORNODP " : Não permitidos no nome/apelido !"
#define ERRORPASSMATCH "As senhas não combinam."

/* pieces */
#define TLONGR "Torre"
#define TLONGP "Peão"
#define TLONGN "Cavalo"
#define TLONGK "Rei"
#define TLONGQ "Rainho"
#define TLONGB "Bispo"
#define TEMPTY ""

#define TWHITE "Branca"
#define TBLACK "Preta"

#define TSHORTR "R"
#define TSHORTP "P"
#define TSHORTN "N"
#define TSHORTK "K"
#define TSHORTQ "Q"
#define TSHORTB "B"
#define TSHORTE " "

/* Special Moves */
#define SMCKS "Pequeno Roque"
#define SMCQS	"Grande Roque"
#define SMEP "En Passant"
#define MATE "Mate"
#define CHECK "Check"

/* Special Actions */
#define SPECIALRESENT "Reenviar senha"
#define SPECIALGIVEUP "Desistir"
#define SPECIALREMIS "Empate?"
#define SPECIALSETTINGS "Configurações"
#define SPECIALDO "Faça"
#define SPECIALSETTINGSCHANGED "Suas configurações foram salvas!"
#define SPECIALLOGOUT "Finalizar sessão"

/* Messages */
#define MSGOK "Ok"
#define MSGYES "Sim"
#define MSGNO "Não"
#define MSGACCEPT "Aceitar"
#define MSGDIS "Não aceitar"

/* Admin Mode and Games List */
#define ADMIN_SPECIFY_PASS "Você tem que digitar uma senha !"                              
#define ADMIN_PASS_OLD "Senha antiga"
#define ADMIN_PASS "Senha"   
#define ADMIN_PASS_RE "Redigite a senha"
#define ADMIN_OK "Ok"
#define ADMIN_EOPASS "Não foi possível acessar o arquivo de senhas"                                
#define ADMIN_EKEY      "Chave de encriptação errada, criptografia desabilitada !"                                     
#define ADMIN_PASSDIFFER "As senhas não combinam"
#define ADMIN_TABLE_START "Iniciar"
#define ADMIN_TABLE_ACC "Último acesso"
#define ADMIN_TABLE_P1 "Jogador 1" 
#define ADMIN_TABLE_P2 "Jogador 2" 
#define ADMIN_TABLE_PW "Senha"   
#define ADMIN_DELETE "Deletar"
#define ADMIN_END "Voltar para o login"
#define ADMIN_PWSAVED "Senha salva!"
#define ADMIN_WRONGPASS "Senha errada!"
#define ADMIN_NUM " # "
#define ADMIN_AGAINST "Contra"
#define ADMIN_STATUS "Status"
#define ADMIN_STATUS_YOU "Movivemto"
#define ADMIN_STATUS_NOT_YOU "Espere"
#define ADMIN_STATUS_FIN "Terminado"
#define ADMIN_GAMES_OF "Jogos de"

/* Arrows */
#define ARROW_T_L "Esquerda"
#define ARROW_T_R "Direita"
#define ARROW_T_LL "Início"
#define ARROW_T_RR "Fim"

/* other icons */
#define SWAP_TEXT0 "wb"
#define SWAP_TEXT1 "bw"
#define REDFRAME_TEXT "R"
#define SWAP_TEXT0_LONG "Branco no topo"
#define SWAP_TEXT1_LONG "Preto no topo"
#define REDFRAME_TEXT_LONG "Mostrar todos movimentos disponíveis"
