/* charset */
#define CHARSET "iso-8859-1"

/* global */
#define CALLITFROMBROWSER "You should *not* call this program directly !"

/* start */
#define STARTGAMENICK1 "Nickname of Player 1"
#define STARTGAMENICK2 "Nickname of Player 2"
#define STARTGAMELEAVEBLANK "Leave the second player blank if you have none."
#define STARTGAMEMAIL1 "Mailaddress of Player 1"
#define STARTGAMEMAIL2 "Mailaddress of Player 2"
#define STARTHASWHITE "This Player is white"
#define STARTNEW "Start new Game"
#define STARTGAMEID "Game ID"
#define STARTRESUME "Resume Game"
#define STARTFINISH "The new game is opened. Look at your mailbox !"
#define STARTWAIT "Now you have to wait for your opponent...."
#define STARTSEARCH "Join one of the following games"
#define STARTNUMBERGAMES "games"
#define STARTNUMBEROGAMES "open games"
#define STARTANEWGAME "Start a new game"
#define STARTRESUMEAGAME "Resume a game"
#define STARTSENDMYGAMES "Send me my games"
#define STARTMYMAIL "My Emailaddress"
#define STARTSEND "Send"
#define STARTSENDNOMAIL "Only list games in web"

/* mail */
#define MAILDEAR "Dear"
#define MAILMOVE "Its your move now. Your password is"
#define MAILURLRESUME "Open the following link to resume game"
#define MAILURLVIEW "Open the following link to view game"
#define MAILDONE "Your move is done."
#define MAILINVITE "You have been invited to a chess match !"
#define MAILID "Your game-id is"
#define MAILBOARD "The Board is located at"
#define MAILWINNER "You have won the game !"
#define MAILOPCHECK "Your opponent is in check !"
#define MAILPASS "The Password has been mailed to you !"
#define MAILREMIS "Remis was requested !"
#define MAILISREMIS "Remis !"
#define MAILGIVESUP "%s gives up !"
#define MAILHIT "Hit"
#define MAILFINISHED "This game is finished !"
#define MAILAGAINST "against"
#define MAILYOUWHITE "You have the white uppercase pieces !"
#define MAILYOUBLACK "You have the black lowercase pieces !"

/* resume */
#define RESTITLE "Chess match: %s against %s"
#define RESTURN "It's %s's turn with %s !"
#define RESTURNR "It's your choice, %s !"
#define RESLAST "The last move was"
#define RESPASS "Please enter the given password"
#define RESMOVES "Moves so far"
#define RESCHANGE "Please select a piece to change with the moved Pawn !"
#define RESMESSAGE "Message"
#define RESREQUESTSENT "Your request has been sent !"
#define RESREMREQ "Remis was requested !"
#define RESMAILOF "Mailaddress of %s"
#define RESID "Game ID"
#define RESSTART "Game started at"
#define RESFIXPASS "Fixed Password"
#define RESFIXPASSA "Retype fixed Password"
#define RESPASSWARN "Just to remind you: ITS NOT SECURE !<br>Everybody could get it with ease.<br>So don't use your standard passwords !"
#define RESNOMAILTOME "I don't want to receive any mails during the game."

/* moved */
#define MOVEDFINISH "Your move has been sent. Please click here to see the board again !"
#define MOVECANC "Your move has been cancelled !"

/* sendgames */
#define SENDGAMESPLAY "Your are playing the following games"
#define SENDGAMESBYE "Have a nice day !"
#define SENDGAMESBACK "Your games have been sent to your email-address !"
#define SENDGAMENOTFOUND "There are no games using this email-address !"
#define SENDBACK "Back to Login"

/* errors */
#define ERRORDEFAULT "Error"
#define ERRORCREATE "Unable to create file"
#define ERROROPEN "Unable to open file"
#define ERRORPIPE "Unable to open pipe"
#define ERRORID "The requested game does not exist !"
#define ERRORMEM "Out of Memory"
#define ERRORMOV "Error moving piece"
#define ERRORPASS "Wrong or no Password supplied !"
#define ERRORGAMEDIR "Unable to open game dir !"
#define ERRORGAMECOR "The game data is corrupt !"
#define ERRORMAILVALID "Invalid Mailaddress !"
#define ERRORMISMAIL "Missing Mailaddress !"
#define ERRORMISNICK "Missing Nickname !"
#define ERRORNICKLONG "The Nickname is too long !"
#define ERRORMAILLONG "The Mailaddress is too long !"
#define ERRORPASSLONG "The Password is too long !"
#define ERROROLDBOARD "Your Board shows an old move.... You have to reload the game !"
#define ERRORILLEGAL "Illegal Move !"
#define ERRORNODP "No : allowed in Username !"
#define ERRORPASSMATCH "The passwords dont match !"

/* pieces */
#define TLONGR "Rook"
#define TLONGP "Pawn"
#define TLONGN "Knight"
#define TLONGK "King"
#define TLONGQ "Queen"
#define TLONGB "Bishop"
#define TEMPTY ""

#define TWHITE "White"
#define TBLACK "Black"

#define TSHORTR "R"
#define TSHORTP "P"
#define TSHORTN "N"
#define TSHORTK "K"
#define TSHORTQ "Q"
#define TSHORTB "B"
#define TSHORTE " "

/* Special Moves */
#define SMCKS "Castle King Side"
#define SMCQS	"Castle Queen Side"
#define SMEP "En Passant"
#define MATE "Mate"
#define CHECK "Check"

/* Special Actions */
#define SPECIALRESENT "Resent Password"
#define SPECIALGIVEUP "Give Up"
#define SPECIALREMIS "Remis?"
#define SPECIALSETTINGS "Settings"
#define SPECIALDO "Do It"
#define SPECIALSETTINGSCHANGED "Your settings have been saved !"
#define SPECIALLOGOUT "Logout"

/* Messages */
#define MSGOK "Ok"
#define MSGYES "Yes"
#define MSGNO "No"
#define MSGACCEPT "Accept"
#define MSGDIS "Discline"

/* Admin Mode and Games List */
#define ADMIN_SPECIFY_PASS "You have to specify a password !"
#define ADMIN_PASS_OLD "Old Password"
#define ADMIN_PASS "Password"
#define ADMIN_PASS_RE "Retype Password"
#define ADMIN_OK "Ok"
#define ADMIN_EOPASS "Unable to access password-file !"
#define ADMIN_EKEY	"Wrong cryption key, cryption disabled !"
#define ADMIN_PASSDIFFER "The passwords differ !"
#define ADMIN_TABLE_START "Begin"
#define ADMIN_TABLE_ACC "Last Access"
#define ADMIN_TABLE_P1 "Player 1"
#define ADMIN_TABLE_P2 "Player 2"
#define ADMIN_TABLE_PW "Password"
#define ADMIN_DELETE "Delete"
#define ADMIN_END "Back to login"
#define ADMIN_PWSAVED "Password saved !"
#define ADMIN_WRONGPASS "Wrong Password !"
#define ADMIN_NUM " # "
#define ADMIN_AGAINST "Against"
#define ADMIN_STATUS "Status"
#define ADMIN_STATUS_YOU "Move"
#define ADMIN_STATUS_NOT_YOU "Wait"
#define ADMIN_STATUS_FIN "Finished"
#define ADMIN_GAMES_OF "Games of"

/* Arrows */
#define ARROW_T_L "Left"
#define ARROW_T_R "Right"
#define ARROW_T_LL "Begin"
#define ARROW_T_RR "End"

/* other icons */
#define SWAP_TEXT0 "wb"
#define SWAP_TEXT1 "bw"
#define REDFRAME_TEXT "R"
#define SWAP_TEXT0_LONG "White at the top"
#define SWAP_TEXT1_LONG "Black at the top"
#define REDFRAME_TEXT_LONG "Show me all possible moves"
