/* charset */
#define CHARSET "iso-8859-1"

/* global */
#define CALLITFROMBROWSER "Non devi lanciare questo programma direttamente!"

/* start */
#define STARTGAMENICK1 "Soprannome del Giocatore 1"
#define STARTGAMENICK2 "Soprannome del Giocatore 2"
#define STARTGAMELEAVEBLANK "Lascia il secondo giocatore vuoto, se non ne hai nessuno."
#define STARTGAMEMAIL1 "Indirizzo di posta del Giocatore 1"
#define STARTGAMEMAIL2 "Indirizzo di posta del Giocatore 2"
#define STARTHASWHITE "Questo giocatore ha i bianchi"
#define STARTNEW "Inizia nuova partita"
#define STARTGAMEID "Identificativo Partita"
#define STARTRESUME "Riprendi Partita"
#define STARTFINISH "Una nuova partita e' iniziata. Guarda nella tua casella di posta!"
#define STARTWAIT "Ora devi aspettare il tuo sfidante..."
#define STARTSEARCH "Unisciti a una di queste partite"
#define STARTNUMBERGAMES "partite"
#define STARTNUMBEROGAMES "partite aperte"
#define STARTANEWGAME "Inizia nuova partita"
#define STARTRESUMEAGAME "Riprendi Partita"
#define STARTSENDMYGAMES "Spediscimi le mie partite"
#define STARTMYMAIL "Mio indirizzo di posta"
#define STARTSEND "Invia"
#define STARTSENDNOMAIL "Mostra solo le partite sul web"

/* mail */
#define MAILDEAR "Caro"
#define MAILMOVE "E' il momento della tua mossa. La tua password e'"
#define MAILURLRESUME "Apri il seguente link per riprendere la partita"
#define MAILURLVIEW "Apri il seguente link per vedere la partita"
#define MAILDONE "La tua mossa e' stata eseguita."
#define MAILINVITE "Sei stato invitato per una partita di scacchi !"
#define MAILID "L' identificativo della partita e'"
#define MAILBOARD "La scacchiera e' su"
#define MAILWINNER "Hai vinto la partita !"
#define MAILOPCHECK "Il tuo avversario e' sotto scacco !"
#define MAILPASS "La password ti e' stata spedita !"
#define MAILREMIS "E' stata richiesta patta !"
#define MAILISREMIS "Patta !"
#define MAILGIVESUP "%s lascia !"
#define MAILHIT "Hit"
#define MAILFINISHED "La partita e' finita !"
#define MAILAGAINST "contro"
#define MAILYOUWHITE "Tu hai i pezzi maiuscoli bianchi !"
#define MAILYOUBLACK "Tu hai i pezzi minuscoli neri !"

/* resume */
#define RESTITLE "Partita di scacchi: %s contro %s"
#define RESTURN "E' il turno di %s contro %s !"
#define RESTURNR "E' la tua scelta, %s !"
#define RESLAST "L' ultima mossa e' stata"
#define RESPASS "Inserisci la password"
#define RESMOVES "Mosse piu' vecchie"
#define RESCHANGE "Sceglie il pezzo da cambiare con la pedina !"
#define RESMESSAGE "Messaggio"
#define RESREQUESTSENT "La tua richiesta e' stata spedita !"
#define RESREMREQ "E' stata richiesta patta !"
#define RESMAILOF "Indirizzo di posta di %s"
#define RESID "Identificativo partita"
#define RESSTART "Partita inizita il"
#define RESFIXPASS "Password permanente"
#define RESFIXPASSA "Ridigita Password permanente"
#define RESPASSWARN "Ti ricordo: NON E' SICURA !<br>Chiunque puo' scoprirla facilmente.<br>Non usare le solite password !"
#define RESNOMAILTOME "Non voglio ricevere nessuna email durante il gioco."

/* moved */
#define MOVEDFINISH "La tua mossa e' stata spedita. Clicca qui per rivedere la scacchiera !"
#define MOVECANC "La tua mossa e' stata cancellata !"

/* sendgames */
#define SENDGAMESPLAY "Stai giocando le seguenti partite"
#define SENDGAMESBYE "Buona giornata !"
#define SENDGAMESBACK "Le tue partite sono state spedite al tuo indirizzo di posta!"
#define SENDGAMENOTFOUND "Non ci sono partite che usano questo indirizzo di posta !"
#define SENDBACK "Ritorna al login"

/* errors */
#define ERRORDEFAULT "Errore"
#define ERRORCREATE "Impossibile creare il file"
#define ERROROPEN "Impossibile aprire il file"
#define ERRORPIPE "Impossibile aprire la pipe"
#define ERRORID "La partita richiesta non e' disponibile !"
#define ERRORMEM "Finita la memoria"
#define ERRORMOV "Errore nel muovere il pezzo"
#define ERRORPASS "Falsa o nessuna password inserita !"
#define ERRORGAMEDIR "Impossibile aprire la directory delle partite!"
#define ERRORGAMECOR "I dati della partita sono corrotti !"
#define ERRORMAILVALID "Indirizzo di posta non valido !"
#define ERRORMISMAIL "Indirizzo di posta mancante !"
#define ERRORMISNICK "Soprannome mancante !"
#define ERRORNICKLONG "Il soprannome e' troppo lungo !"
#define ERRORMAILLONG "L' indirizzo di posta e' troppo lungo !"
#define ERRORPASSLONG "La password e' troppo lunga !"
#define ERROROLDBOARD "La tua scacchiera mostra una vecchia mossa.... Devi ricaricare la partita !"
#define ERRORILLEGAL "Mossa non permessa !"
#define ERRORNODP "Non permesso nell' Username !"
#define ERRORPASSMATCH "Le password non coincidono !"

/* pieces */
#define TLONGR "Torre"
#define TLONGP "Pedino"
#define TLONGN "Cavallo"
#define TLONGK "Re"
#define TLONGQ "Regina"
#define TLONGB "Alfiere"
#define TEMPTY ""

#define TWHITE "Bianco"
#define TBLACK "Nero"

#define TSHORTR "R"
#define TSHORTP "P"
#define TSHORTN "N"
#define TSHORTK "K"
#define TSHORTQ "Q"
#define TSHORTB "B"
#define TSHORTE " "

/* Special Moves */
#define SMCKS "Arrocco"
#define SMCQS	"Arrocco"
#define SMEP "En Passant"
#define MATE "Matto"
#define CHECK "Scacco"

/* Special Actions */
#define SPECIALRESENT "Rispedisci password"
#define SPECIALGIVEUP "Lascia"
#define SPECIALREMIS "Patta?"
#define SPECIALSETTINGS "Opzioni"
#define SPECIALDO "Esegui"
#define SPECIALSETTINGSCHANGED "Le tue opzioni sono state salvate !"
#define SPECIALLOGOUT "Logout"

/* Messages */
#define MSGOK "Ok"
#define MSGYES "SI"
#define MSGNO "NO"
#define MSGACCEPT "Accetta"
#define MSGDIS "Rifiuta"

/* Admin Mode and Games List */
#define ADMIN_SPECIFY_PASS "Devi specificare la password !"
#define ADMIN_PASS_OLD "Vecchia Password"
#define ADMIN_PASS "Password"
#define ADMIN_PASS_RE "Reinserisci la Password"
#define ADMIN_OK "Ok"
#define ADMIN_EOPASS "Non posso accedere al file della password !"
#define ADMIN_EKEY	"Chiave di crittazione sbagliata, crittazione disabilitata !"
#define ADMIN_PASSDIFFER "Le password non coincidono !"
#define ADMIN_TABLE_START "Inizia"
#define ADMIN_TABLE_ACC "Ultimo accesso"
#define ADMIN_TABLE_P1 "Giocatore 1"
#define ADMIN_TABLE_P2 "Giocatore 2"
#define ADMIN_TABLE_PW "Password"
#define ADMIN_DELETE "Cancella"
#define ADMIN_END "Ritorna al login"
#define ADMIN_PWSAVED "Password salvata !"
#define ADMIN_WRONGPASS "Password Sbagliata!"
#define ADMIN_NUM " # "
#define ADMIN_AGAINST "Contro"
#define ADMIN_STATUS "Stato"
#define ADMIN_STATUS_YOU "Mossa"
#define ADMIN_STATUS_NOT_YOU "Attendi"
#define ADMIN_STATUS_FIN "Finito"
#define ADMIN_GAMES_OF "Partita di"

/* Arrows */
#define ARROW_T_L "Sinistra"
#define ARROW_T_R "Destra"
#define ARROW_T_LL "Inizio"
#define ARROW_T_RR "Fine"

/* other icons */
#define SWAP_TEXT0 "wb"
#define SWAP_TEXT1 "bw"
#define REDFRAME_TEXT "R"
#define SWAP_TEXT0_LONG "Bianchi in alto"
#define SWAP_TEXT1_LONG "Neri in alto"
#define REDFRAME_TEXT_LONG "Mostrami le possibili mosse"
